version: 0.2

env:
  variables:
    REPOSITORY_URI: '883062483828.dkr.ecr.us-east-1.amazonaws.com/blog-starter-app-ecr'
    DOCKER_TAG: 'latest'

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo Building the Docker image...
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$DOCKER_TAG .
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$DOCKER_TAG
